export type Book = {
  id: number;
  title: string;
  owner_id?: number;
  created_at?: string;
  updated_at?: string;
  author?: string;
  genre?: string;
  isbn?: string;
  cover_path?: string;
  description?: string;
  price?: number;
  stock?: number;
  current_page?: number;
  total_pages?: number | null;
  progress_percentage?: number;
  last_read_time?: string | null;
  notes?: string | null;
  file_type?: string | null;
  file_url?: string | null;
};