"""Add indexed_at timestamp to document_chunks

Revision ID: 7ef760e043d2
Revises: e8f24d8a9b11
Create Date: 2026-05-19 17:51:44.865632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ef760e043d2'
down_revision: Union[str, None] = 'e8f24d8a9b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'indexed_at')
    # ### end Alembic commands ###
