"""add personalization fields to users

Revision ID: e7e8dfc85356
Revises: d11d65704986
Create Date: 2026-05-19 18:26:22.399232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e8dfc85356'
down_revision: Union[str, None] = 'd11d65704986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('explanation_level', sa.String(), nullable=False, server_default='intermediate'))
    op.add_column('users', sa.Column('study_goal', sa.String(), nullable=True))
    op.add_column('users', sa.Column('weak_topics', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('frequently_reviewed_tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'frequently_reviewed_tags')
    op.drop_column('users', 'weak_topics')
    op.drop_column('users', 'study_goal')
    op.drop_column('users', 'explanation_level')
    # ### end Alembic commands ###
